version: "3.9"
services:
  ##Database config
  mysql:
    image: mysql:8.0.31
    ports:
      - "6603:3306"
    environment:
      - MYSQL_DATABASE=restaurant
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    profiles:
      - db
      - mysql
    volumes:
      - .data/db:/var/lib/mysql
      - ./deployments/docker/mysql/init.sql:/docker-entrypoint-initdb.d/1-init-databases.sql