version: "3.9"
services:
  ra-service:
    container_name: ra-service
    image: ra-service:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8989:8989"
      - "9192:9192"
    depends_on:
      - mysql
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: "2"
#          memory: 500M

  ##Database config
  mysql:
    container_name: ra-db
    image: mysql:8.0.31
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    volumes:
      - .data/db:/var/lib/mysql
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.47.0
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.2
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/var/lib/grafana