server:
  port: 8989

# flyway:
#   baseline-on-migrate: true
#   url: jdbc:mysql://localhost:6603/mysql
#   schemas: ra
#   user: "root"
#   password: "root"

spring:
  flyway:
    baselineOnMigrate: true
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}:6603/ra
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: false

logging:
  level:
    # root: DEBUG
    # org.springframework.web: DEBUG
    org:
      hibernate:
        DEBUG
        # sql: debug
        # type:
        #   descriptor:
        #     sql: TRACE

management:
  security:
    enabled: false
  server:
    port: 9192
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    shutdown:
      enabled: true
    info:
      env:
        enabled: true
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans