apiVersion: v1
kind: Service
metadata:
  name: ra-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8989
  selector:
    app: ra-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra-service
  labels:
    app: ra-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ra-service 
  template:
    metadata:
      labels:
        app: ra-service
    spec:
      containers:
        - name: ra-service
          image: ra-service-k8s:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
