apiVersion: v1
kind: Service
metadata:
  name: ra-service
  labels:
    operated-prometheus: "true"
spec:
  type: NodePort
  ports:
#    - port: 8080
#      targetPort: service-port
    - name: web
      port: 9090
      targetPort: web
  selector:
    app: ra-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra-service
  labels:
    app: ra-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ra-service 
  template:
    metadata:
      labels:
        app: ra-service
    spec:
      containers:
        - name: ra-service
          image: ra-service-k8s:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: service-port
              containerPort: 8989
            - name: web
              containerPort: 9192
